# Generated by Django 2.2.16 on 2020-10-29 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('nombre', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MisionVision',
            fields=[
                ('numero', models.CharField(max_length=115, primary_key=True, serialize=False)),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SliderGaleria',
            fields=[
                ('numero', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('foto', models.ImageField(null=True, upload_to='galeria')),
            ],
        ),
        migrations.CreateModel(
            name='SliderIndex',
            fields=[
                ('numero', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('foto', models.ImageField(null=True, upload_to='index')),
            ],
        ),
    ]
